### ISSUE TITLE
LateInitializationError: Field '_webViewController@139173288' has already been initialized.

### ISSUE THREAD

**Issue by ShirishAryal** [chandrabezzo/flutter_summernote#51]
``` 
late final WebViewController? _webViewController;
....
@override
  void dispose() {
    if (_webViewController != null) {
      _webViewController = null;
    }
    super.dispose();
  }
  ```
 Setting _webViewController  =null on dispose causing this error.
 So every time we dispose the page containing summer_note "LateInitializationError: Field '_webViewController@139173288' has already been initialized." is thrown.

**Comment by Devandhiran637** [comment]
have you got any solution

**Comment by remymumoh** [comment]
no solution can we create a pull request to get merged by the developer?

a work around import this 
```
flutter_summernote:
        git:
            url: https://github.com/remymumoh/flutter_summernote.git
            ref: v2.0.0   
```
